# Generated by Django 5.2.17 on 2026-09-21 10:31

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Aim for 50–60 characters. Falls back to the page title.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Aim for 140–160 characters. Falls back to the excerpt.', max_length=320)),
                ('focus_keyword', models.CharField(blank=True, max_length=120)),
                ('canonical_url', models.URLField(blank=True, help_text="Leave blank to use this page's public URL.")),
                ('robots', models.CharField(choices=[('index,follow', 'Index and follow'), ('noindex,follow', 'Do not index; follow links'), ('noindex,nofollow', 'Do not index or follow')], default='index,follow', max_length=24)),
                ('social_title', models.CharField(blank=True, max_length=100)),
                ('social_description', models.CharField(blank=True, max_length=240)),
                ('social_image', models.ImageField(blank=True, upload_to='social/%Y/%m/')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('short_description', models.TextField(blank=True)),
                ('body', tinymce.models.HTMLField(blank=True, help_text='Evergreen introduction shown below the latest analysis.')),
                ('nav_group', models.CharField(choices=[('currencies', 'Currencies Forecast'), ('commodities', 'Commodities Forecast'), ('markets', 'Other Markets'), ('education', 'Education')], default='markets', max_length=24)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('featured_image', models.ImageField(blank=True, upload_to='categories/%Y/%m/')),
                ('legacy_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('file', models.ImageField(blank=True, upload_to='library/%Y/%m/')),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=220)),
                ('caption', models.TextField(blank=True)),
                ('credit', models.CharField(blank=True, max_length=180)),
                ('legacy_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Aim for 50–60 characters. Falls back to the page title.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Aim for 140–160 characters. Falls back to the excerpt.', max_length=320)),
                ('focus_keyword', models.CharField(blank=True, max_length=120)),
                ('canonical_url', models.URLField(blank=True, help_text="Leave blank to use this page's public URL.")),
                ('robots', models.CharField(choices=[('index,follow', 'Index and follow'), ('noindex,follow', 'Do not index; follow links'), ('noindex,nofollow', 'Do not index or follow')], default='index,follow', max_length=24)),
                ('social_title', models.CharField(blank=True, max_length=100)),
                ('social_description', models.CharField(blank=True, max_length=240)),
                ('social_image', models.ImageField(blank=True, upload_to='social/%Y/%m/')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('eyebrow', models.CharField(blank=True, max_length=80)),
                ('excerpt', models.TextField(blank=True)),
                ('body', tinymce.models.HTMLField()),
                ('featured_image', models.ImageField(blank=True, upload_to='pages/%Y/%m/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='published', max_length=16)),
                ('show_in_sitemap', models.BooleanField(default=True)),
                ('legacy_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(help_text='Must start with /.', max_length=500, unique=True)),
                ('new_path', models.CharField(max_length=500)),
                ('permanent', models.BooleanField(default=True)),
                ('hits', models.PositiveIntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Elliott Wave Monitor', max_length=100)),
                ('tagline', models.CharField(default='Independent Elliott Wave forecasts, market structure and trading education.', max_length=180)),
                ('hero_title', models.CharField(default='See the market structure before the move', max_length=180)),
                ('hero_text', models.TextField(default='Actionable Elliott Wave analysis across forex, commodities, crypto and global indices.')),
                ('logo', models.ImageField(blank=True, upload_to='branding/')),
                ('default_social_image', models.ImageField(blank=True, upload_to='branding/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('telegram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('x_url', models.URLField(blank=True, verbose_name='X / Twitter URL')),
                ('footer_disclaimer', models.TextField(blank=True)),
                ('google_site_verification', models.CharField(blank=True, max_length=160)),
                ('google_analytics_id', models.CharField(blank=True, max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('url', models.CharField(help_text='Use a local path such as /education/ or a full URL.', max_length=300)),
                ('group', models.CharField(choices=[('primary', 'Primary navigation'), ('footer', 'Footer navigation')], default='primary', max_length=24)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.menuitem')),
            ],
            options={
                'ordering': ['group', 'order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Aim for 50–60 characters. Falls back to the page title.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Aim for 140–160 characters. Falls back to the excerpt.', max_length=320)),
                ('focus_keyword', models.CharField(blank=True, max_length=120)),
                ('canonical_url', models.URLField(blank=True, help_text="Leave blank to use this page's public URL.")),
                ('robots', models.CharField(choices=[('index,follow', 'Index and follow'), ('noindex,follow', 'Do not index; follow links'), ('noindex,nofollow', 'Do not index or follow')], default='index,follow', max_length=24)),
                ('social_title', models.CharField(blank=True, max_length=100)),
                ('social_description', models.CharField(blank=True, max_length=240)),
                ('social_image', models.ImageField(blank=True, upload_to='social/%Y/%m/')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Used on cards and as the fallback meta description.')),
                ('body', tinymce.models.HTMLField()),
                ('author_name', models.CharField(default='EWM Team', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('featured_image', models.ImageField(blank=True, upload_to='articles/%Y/%m/')),
                ('featured_image_url', models.URLField(blank=True, max_length=500)),
                ('featured_image_alt', models.CharField(blank=True, max_length=220)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('legacy_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_categories', models.ManyToManyField(blank=True, related_name='additional_articles', to='content.category')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='content.category')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='content_art_status_9dc828_idx'), models.Index(fields=['category', 'status', '-published_at'], name='content_art_categor_1a8f08_idx')],
            },
        ),
    ]
