# Generated by Django 5.2.17 on 2026-09-23 09:38

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_arabic_content_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='body_ar',
            field=tinymce.models.HTMLField(blank=True, help_text='Arabic guide shown on the main-language page.', verbose_name='Arabic evergreen guide'),
        ),
        migrations.AlterField(
            model_name='page',
            name='body_ar',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Arabic body'),
        ),
    ]
