# Generated by Django 5.2.17 on 2026-09-23 10:17

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_category_body_ar_alter_page_body_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_ar',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Arabic body'),
        ),
        migrations.AddField(
            model_name='article',
            name='excerpt_ar',
            field=models.TextField(blank=True, help_text='Leave blank to generate the first 15 Arabic words when an Arabic body is present.', verbose_name='Arabic excerpt'),
        ),
        migrations.AddField(
            model_name='article',
            name='featured_image_alt_ar',
            field=models.CharField(blank=True, max_length=220, verbose_name='Arabic image alt text'),
        ),
        migrations.AddField(
            model_name='article',
            name='focus_keyword_ar',
            field=models.CharField(blank=True, max_length=120, verbose_name='Arabic focus keyword'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description_ar',
            field=models.CharField(blank=True, max_length=320, verbose_name='Arabic meta description'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title_ar',
            field=models.CharField(blank=True, max_length=70, verbose_name='Arabic SEO title'),
        ),
        migrations.AddField(
            model_name='article',
            name='social_description_ar',
            field=models.CharField(blank=True, max_length=240, verbose_name='Arabic social description'),
        ),
        migrations.AddField(
            model_name='article',
            name='social_title_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Arabic social title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ar',
            field=models.CharField(blank=True, max_length=220, verbose_name='Arabic title'),
        ),
        migrations.AddField(
            model_name='category',
            name='focus_keyword_ar',
            field=models.CharField(blank=True, max_length=120, verbose_name='Arabic focus keyword'),
        ),
        migrations.AddField(
            model_name='page',
            name='focus_keyword_ar',
            field=models.CharField(blank=True, max_length=120, verbose_name='Arabic focus keyword'),
        ),
    ]
