# Generated by Django 5.2.17 on 2026-09-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_sitesettings_facebook_url_sitesettings_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, help_text='Local path or full URL. Leave blank for a dropdown heading or coming-soon item.', max_length=300),
        ),
    ]
