# Generated by Django 5.2.17 on 2026-10-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_sitesettings_footer_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('path', models.CharField(max_length=300)),
                ('language', models.CharField(max_length=2)),
                ('device', models.CharField(max_length=12)),
                ('referrer', models.CharField(default='Direct / unknown', max_length=253)),
                ('views', models.PositiveBigIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Statistics',
                'verbose_name_plural': 'Statistics',
                'default_permissions': ('view',),
                'constraints': [models.UniqueConstraint(fields=('date', 'path', 'language', 'device', 'referrer'), name='unique_traffic_daily_bucket')],
            },
        ),
    ]
