# Generated by Django 5.2.17 on 2026-10-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_trafficdaily'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trafficdaily',
            name='unique_traffic_daily_bucket',
        ),
        migrations.AddField(
            model_name='trafficdaily',
            name='country',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddConstraint(
            model_name='trafficdaily',
            constraint=models.UniqueConstraint(fields=('date', 'path', 'language', 'device', 'referrer', 'country'), name='unique_traffic_daily_bucket'),
        ),
    ]
