# Generated by Django 5.2.17 on 2026-10-10 15:49

from django.db import migrations, models


def unpublish_litecoin(apps, schema_editor):
    # Retain the archive's editorial content and every related article.
    apps.get_model('content', 'Category').objects.filter(slug='ltcusd-forecast').update(is_published=False, is_visible=False)
    apps.get_model('content', 'MenuItem').objects.filter(url__in=[
        '/ltcusd-forecast/', '/en/ltcusd-forecast/',
        'https://elliottwavemonitor.com/ltcusd-forecast/',
        'https://elliottwavemonitor.com/en/ltcusd-forecast/',
    ]).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_remove_trafficdaily_unique_traffic_daily_bucket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Uncheck to unpublish the archive page in both languages. Its articles remain available independently.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_logo',
            field=models.ImageField(blank=True, help_text='Optional logo for the dark footer. Use a tightly cropped, transparent PNG or WebP with white/light artwork. It fits within 240 × 110 px without stretching. Leave blank to keep the existing footer logo.', upload_to='branding/footer/', verbose_name='Footer logo'),
        ),
        migrations.RunPython(unpublish_litecoin, migrations.RunPython.noop),
    ]
