# Generated by Django 5.2.17 on 2026-10-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_footer_and_archive_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_logo',
            field=models.ImageField(blank=True, help_text='Optional logo for the dark footer. Use a tightly cropped, transparent PNG or WebP with white/light artwork. It fits within 168 × 77 px without stretching. Leave blank to keep the existing footer logo.', upload_to='branding/footer/', verbose_name='Footer logo'),
        ),
    ]
